---

- name: Create cache dir
  file:
    path: "{{ alp.cache }}"
    state: directory

- name: Download ALP image to cache if needed
  get_url:
    dest: "{{ alp_image.cached }}"
    url: "{{ alp_image.url }}"
    checksum: "{{ alp_image.checksum}}"
    mode: 0644
  register: alp_image_download

- name: Report image that was downloaded
  debug:
    msg: >-
      Selected image available as '{{ alp_image.cached }}'
