---

# Use a cache dir in /var/tmp to avoid path resolution issues
# when switching between different users.
alp_cache_dir: "{{ ['', 'var', 'tmp', 'alp'] | join('/') }}"

alp:
  image_base_urls:
    build: https://download.opensuse.org/repositories/SUSE:/ALP/images/
    snapshot: https://download.opensuse.org/repositories/SUSE:/ALP:/PUBLISH/images/
  build_types:
    - build
    - snapshot
  image_types:
    - kvm
    - kvm_encrypted
  cache:
    images: "{{ [alp_cache_dir, 'images'] | join('/') }}"
    workloads: "{{ [alp_cache_dir, 'workloads'] | join('/') }}"
