---

- name: Check configuation settings are setup and appropriate
  hosts: localhost
  gather_facts: false
  tasks:

    - name: Check that required settings files are present
      ansible.builtin.stat:
        path: "{{ [playbook_dir | dirname, 'settings', item] | join('/') }}"
      loop: "{{ required_settings }}"
      register: stat_required_settings

    - name: Initialise required settings files if not found
      ansible.builtin.copy:
        src: "{{ [playbook_dir | dirname, 'settings', item.item] | join('/') }}.example"
        dest: "{{ [playbook_dir | dirname, 'settings', item.item] | join('/') }}"
        mode: "0644"
      loop: "{{ stat_required_settings.results }}"
      loop_control:
        label: "{{ item.item }}"
      register: copy_required_settings

    - name: Report if required settings files were created  # noqa no-handler
      ansible.builtin.debug:
        msg: >-
          Required settings files have been setup.
          Please customise as needed.
      when:
        - copy_required_settings is changed

    - name: Verify ALP vm_configs has been defined
      ansible.builtin.assert:
        that:
          - vm_configs is defined
        success_msg: >-
          'vm_configs' has been defined.
        fail_msg: >-
          No 'vm_configs' settings detected.
          Did you copy settings/vms.yml.example to settings/vms.yml and
          customise it?

    - name: Verify ALP vnet_configs has been defined
      ansible.builtin.assert:
        that:
          - vnet_configs is defined
        success_msg: >-
          'vnet_configs' has been defined.
        fail_msg: >-
          No 'vnet_configs' settings detected.
          Did you copy settings/vnets.yml.example to settings/vnets.yml and
          customise it?
