---

#
# Dynamically define the alp_vms group based upon settings/vms.yml
# VM configuration.
#

- name: Dynamically define ALP VMs group
  hosts: localhost
  connection: local
  gather_facts: false
  roles:
    - setup_ssh
  tasks:

    - name: Define alp_vms group if not already defined
      ansible.builtin.include_role:
        name: alp_vm
        tasks_from: define_alp_vms.yml
      when:
        - ('alp_vms' not in groups)
