---

alp_image:
  name: "ALP-Dolomite.x86_64-1.0-Default-qcow-Milestone3.qcow2"
  url: "https://updates.suse.com/SUSE/Products/ALP-Dolomite/1.0/x86_64/ALP-Dolomite.x86_64-1.0-Default-qcow-Milestone4.qcow2"
  cached: "{{ alp.cache.images }}/ALP-Dolomite.x86_64-1.0-Default-qcow-Milestone4.qcow2"
  checksum: "sha256:https://updates.suse.com/SUSE/Products/ALP-Dolomite/1.0/x86_64/ALP-Dolomite.x86_64-1.0-Default-qcow-Milestone4.qcow2.sha256"
