---

_alp_version: >-
  {{ alp_version | default('0.0.1') }}

_alp_build_type: >-
  {{ alp_build_type | default('build') }}

_alp_image_type: >-
  {{ alp_image_type | default('kvm') }}

_alp_build_versions: >-
  {{ alp_build_versions | default(alp.default_build_versions) }}

_alp_build_version: >-
  {{ _alp_build_versions[_alp_build_type].prefix ~
     _alp_build_versions[_alp_build_type][_alp_image_type] }}

_alp_arch: >-
  {{ alp_arch | default('x86_64') }}

_alp_image_name: >-
  {{ 'ALP-VM.' ~ _alp_arch ~ '-' ~ _alp_version ~ '-' ~
     _alp_image_type ~ '-' ~ _alp_build_version ~ '.qcow2' }}

_alp_image_url: >-
  {{ alp.image_base_urls[_alp_build_type] ~ '/' ~ _alp_image_name }}

alp_image:
  name: "{{ _alp_image_name }}"
  url: "{{ _alp_image_url }}"
  cached: "{{ alp.cache }}/{{ _alp_image_name }}"
  checksum: "sha256:{{ _alp_image_url }}.sha256"
